config/routes.rb
Scheduler::Application.routes.draw do
  get "confirm/ok"
  get "confirm/staff_ok"

  get "confirm/ng"

  resources :notifications

  devise_for :users

  get "monthly_report/report"

  get "weekly_schedule/weekly"

  root :to => 'home#index'

  match 'lessons/add' => 'lessons#add', :as => :add_lesson

  resources :holidays
  resources :schedule_types
  resources :lessons
  resources :users
  resources :teachers do
    post 'set_availability', :on => :member
  end
  resources :regular_classes do
    post 'create_lessons', :on => :member
  end

  match 'schedule_types/:id/set_holidays' => 'schedule_types#set_holidays', :as => :set_holidays
  match 'lessons/:id/cancel' => 'lessons#cancel', :as => :cancel_lesson
  match 'lessons/:id/sub' => 'lessons#sub', :as => :sub_lesson
  match 'teachers/:id/send_test_mail' => 'teachers#send_test_mail', :as => :send_test_mail
  match 'teachers/:id/send_weekly_schedule_mail' => 'teachers#send_weekly_schedule_mail', :as => :send_weekly_schedule_mail
  match 'teachers/:id/availability' => 'teachers#availability', :as => :availability
  match 'regular_classes/:id/schedule_lessons' => 'regular_classes#schedule_lessons', :as => :schedule_lessons
  match ':date' => 'home#index', :as => :dailyschedule
  match 'weekly/:id' => 'weekly_schedule#weekly', :as => :weekly
  

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  attr_accessible :date, :schedule_type_id

  belongs_to :schedule_type
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_filter :authenticate_user!
  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @holidays }
    end
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
    @holiday = Holiday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @holiday }
    end
  end

  # GET /holidays/new
  # GET /holidays/new.json
  def new
    @holiday = Holiday.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @holiday }
    end
  end

  # GET /holidays/1/edit
  def edit
    @holiday = Holiday.find(params[:id])
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(params[:holiday])

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render json: @holiday, status: :created, location: @holiday }
      else
        format.html { render action: "new" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /holidays/1
  # PUT /holidays/1.json
  def update
    @holiday = Holiday.find(params[:id])

    respond_to do |format|
      if @holiday.update_attributes(params[:holiday])
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday = Holiday.find(params[:id])
    @holiday.destroy

    respond_to do |format|
      format.html { redirect_to holidays_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.haml
= form_for(@holiday) do |f|
  - if @holiday.errors.any?
    #error_explanation
      %h2
        = pluralize(@holiday.errors.count, "error")
        prohibited this holiday from being saved:
      %ul
        - @holiday.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :date
    %br/
    = f.date_select :date
  .actions
    = f.submit

app/views/holidays/edit.html.haml
%h1 Editing holiday
= render 'form'
= link_to 'Show', @holiday
|
\#{link_to 'Back', holidays_path}

app/views/holidays/index.html.haml
%h1 Listing holidays
%table
  %tr
    %th Date
    %th
    %th
    %th
  - @holidays.each do |holiday|
    %tr
      %td= holiday.date
      %td= link_to 'Show', holiday
      %td= link_to 'Edit', edit_holiday_path(holiday)
      %td= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Holiday', new_holiday_path

app/views/holidays/new.html.haml
%h1 New holiday

= render 'form'

= link_to 'Back', holidays_path

app/views/holidays/show.html.haml
%p#notice= notice
%p
  %b Date:
  = @holiday.date
= link_to 'Edit', edit_holiday_path(@holiday)
|
\#{link_to 'Back', holidays_path}