config/routes.rb
Scheduler::Application.routes.draw do
  get "confirm/ok"
  get "confirm/staff_ok"

  get "confirm/ng"

  resources :notifications

  devise_for :users

  get "monthly_report/report"

  get "weekly_schedule/weekly"

  root :to => 'home#index'

  match 'lessons/add' => 'lessons#add', :as => :add_lesson

  resources :holidays
  resources :schedule_types
  resources :lessons
  resources :users
  resources :teachers do
    post 'set_availability', :on => :member
  end
  resources :regular_classes do
    post 'create_lessons', :on => :member
  end

  match 'schedule_types/:id/set_holidays' => 'schedule_types#set_holidays', :as => :set_holidays
  match 'lessons/:id/cancel' => 'lessons#cancel', :as => :cancel_lesson
  match 'lessons/:id/sub' => 'lessons#sub', :as => :sub_lesson
  match 'teachers/:id/send_test_mail' => 'teachers#send_test_mail', :as => :send_test_mail
  match 'teachers/:id/send_weekly_schedule_mail' => 'teachers#send_weekly_schedule_mail', :as => :send_weekly_schedule_mail
  match 'teachers/:id/availability' => 'teachers#availability', :as => :availability
  match 'regular_classes/:id/schedule_lessons' => 'regular_classes#schedule_lessons', :as => :schedule_lessons
  match ':date' => 'home#index', :as => :dailyschedule
  match 'weekly/:id' => 'weekly_schedule#weekly', :as => :weekly
  

end

app/controllers/schedule_types_controller.rb
class ScheduleTypesController < ApplicationController
  before_filter :authenticate_user!
  helper LaterDude::CalendarHelper
  # GET /schedule_types
  # GET /schedule_types.json
  def index
    @schedule_types = ScheduleType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedule_types }
    end
  end

  # GET /schedule_types/1
  # GET /schedule_types/1.json
  def show
    @schedule_type = ScheduleType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule_type }
    end
  end

  # GET /schedule_types/new
  # GET /schedule_types/new.json
  def new
    @schedule_type = ScheduleType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule_type }
    end
  end

  # GET /schedule_types/1/edit
  def edit
    @schedule_type = ScheduleType.find(params[:id])
    @show_calendar = true
    @holidays = []
    Holiday.where("schedule_type_id = ?", params[:id]).pluck("Date(date)").each { |holiday| @holidays.push(holiday.to_s)}
    @holidays.each do |h|
      puts "holiday: " + h
    end
  end

  # GET /schedule_types/1/set_holidays
  def set_holidays
    @schedule_type = ScheduleType.find(params[:id])
  end


  # POST /schedule_types
  # POST /schedule_types.json
  def create
    @schedule_type = ScheduleType.new(params[:schedule_type])

    respond_to do |format|
      if @schedule_type.save
        format.html { redirect_to schedule_types_url, :flash => { :alert => "create" } }
        format.json { render json: @schedule_type, status: :created, location: @schedule_type }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedule_types/1
  # PUT /schedule_types/1.json
  def update
    @schedule_type = ScheduleType.find(params[:id])
    dates = params[:dates]

    Holiday.where("schedule_type_id = ?", params[:id]).each do |h|
      puts "Deleting holiday: " + h.date.to_s
      h.destroy
    end
    dates.each do |d|
      holiday = Holiday.new(:date => d, :schedule_type_id => params[:id])
      puts "Saving holiday for " + d.to_s
      if holiday.save
        puts "Saved"
      end
    end
    respond_to do |format|
      if @schedule_type.update_attributes(params[:schedule_type])
        format.html { redirect_to @schedule_type, notice: 'Schedule type was successfully updated. '}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_types/1
  # DELETE /schedule_types/1.json
  def destroy
    @schedule_type = ScheduleType.find(params[:id])
    @schedule_type.destroy

    respond_to do |format|
      format.html { redirect_to schedule_types_url, :flash => { :alert => "delete" } }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedule_types_helper.rb
module ScheduleTypesHelper
end

app/views/schedule_types/_form.html.haml
:javascript
  $(function(){
    $("td.day").not('.otherMonth').click(function(){
      var checked = $(this).children(".day_checkbox").prop("checked");
      if(checked == true){
        $(this).children(".day_checkbox").prop("checked", false);
        $(this).css("background-color", "#FFFFFF");
      }else if(checked == false){
        $(this).children(".day_checkbox").prop("checked", true);
        $(this).css("background-color", "#666666");
      }
    });
  });
= form_for(@schedule_type) do |f|
  - if @schedule_type.errors.any?
    #error_explanation
      %h2
        = pluralize(@schedule_type.errors.count, "error")
        prohibited this schedule_type from being saved:
      %ul
        - @schedule_type.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :start_date
    %br/
    = f.date_select :start_date
  .field
    = f.label :end_date
    %br/
    = f.date_select :end_date  
  - if @show_calendar
    %p Holidays
    - (0..11).each do |m|
      - d = @schedule_type.start_date >> m
      = calendar_for(d.year, d.month, :yield_surrounding_days => true, :current_month => "%Y-%m") do |day|                                                   |
          if @holidays.include?(day.to_s) then                                                                                                               |
            ["<input class='day_checkbox' type='checkbox' name='dates[]' value='" + day.to_s + "' style='display: none;' checked='checked'>" + day.day.to_s, |
            {:value => day.to_s, :style => "background-color: #666666;"}]                                                                                    |
          else                                                                                                                                               |
            ["<input class='day_checkbox' type='checkbox' name='dates[]' value='" + day.to_s + "' style='display: none;'>" + day.day.to_s,                   |
            {:value => day.to_s}]                                                                                                                            |
          end                                                                                                                                                |
        end                                                                                                                                                  |
  .actions
    = link_to 'Back', schedule_types_path, :class => "btn btn-medium"
    = f.submit 'Update Schedule', :class => "btn btn-primary"

app/views/schedule_types/edit.html.haml
:javascript
  $(function(){

  });
= render 'form'
//= {link_to 'Back', schedule_types_path}

app/views/schedule_types/index.html.haml
:javascript
  $(function(){

  });

- if flash[:alert]
  .alert.alert-success.alert-block.fade.in
    %button.close{:type => "button", :data => {:dismiss => "alert"}}
      &times;
    - case flash[:alert]
      - when "create"
        %h4 Schedule Type Created!
        You can now set the holidays for this type by selecting "Edit".
      - when "delete"
        %h4 Schedule Type Deleted
%br/
= link_to new_schedule_type_path, :class => "btn" do
  %i.icon-plus-sign
  New Schedule Type
%br/
%br/
%table.table.table-bordered.table-hover
  %tr
    %th Name
    %th Start
    %th End
    %th
  - @schedule_types.each do |schedule_type|
    %tr.middle
      %td= schedule_type.name
      %td= schedule_type.start_date
      %td= schedule_type.end_date
      %td
        .btn-toolbar
          .btn-group
            = link_to edit_schedule_type_path(schedule_type), :class => "btn btn-small" do
              %i.icon-edit
              Edit
            = link_to schedule_type, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small" do
              %i.icon-trash
              Delete

app/views/schedule_types/new.html.haml
:javascript
  $(function(){

  });
%h1 New schedule_type
= render 'form'
= link_to 'Back', schedule_types_path

app/views/schedule_types/set_holidays.html.haml
:javascript
  $(function(){

  });
%h1 Setting Holidays
%p Hi!
= link_to 'Show', @schedule_type
|
\#{link_to 'Back', schedule_types_path}

app/views/schedule_types/show.html.haml
:javascript
  $(function(){

  });
%p#notice= notice
%p
  %b Name:
  = @schedule_type.name
= link_to 'Edit', edit_schedule_type_path(@schedule_type)
|
\#{link_to 'Back', schedule_types_path}