config/routes.rb
Scheduler::Application.routes.draw do
  get "confirm/ok"
  get "confirm/staff_ok"

  get "confirm/ng"

  resources :notifications

  devise_for :users

  get "monthly_report/report"

  get "weekly_schedule/weekly"

  root :to => 'home#index'

  match 'lessons/add' => 'lessons#add', :as => :add_lesson

  resources :holidays
  resources :schedule_types
  resources :lessons
  resources :users
  resources :teachers do
    post 'set_availability', :on => :member
  end
  resources :regular_classes do
    post 'create_lessons', :on => :member
  end

  match 'schedule_types/:id/set_holidays' => 'schedule_types#set_holidays', :as => :set_holidays
  match 'lessons/:id/cancel' => 'lessons#cancel', :as => :cancel_lesson
  match 'lessons/:id/sub' => 'lessons#sub', :as => :sub_lesson
  match 'teachers/:id/send_test_mail' => 'teachers#send_test_mail', :as => :send_test_mail
  match 'teachers/:id/send_weekly_schedule_mail' => 'teachers#send_weekly_schedule_mail', :as => :send_weekly_schedule_mail
  match 'teachers/:id/availability' => 'teachers#availability', :as => :availability
  match 'regular_classes/:id/schedule_lessons' => 'regular_classes#schedule_lessons', :as => :schedule_lessons
  match ':date' => 'home#index', :as => :dailyschedule
  match 'weekly/:id' => 'weekly_schedule#weekly', :as => :weekly
  

end

app/controllers/regular_classes_controller.rb
class RegularClassesController < ApplicationController
  before_filter :authenticate_user!
  helper LaterDude::CalendarHelper
 # GET /regular_classes
  # GET /regular_classes.json
  def index
    @sort = params[:sort]
    case params[:sort]
    when "day"
      if params[:schedule_type]
        @regular_classes = RegularClass.order("day ASC").order("start_time ASC").find_all_by_schedule_type_id(params[:schedule_type])
      else
        @regular_classes = RegularClass.order("day ASC").order("start_time ASC").all
      end
    else
      @sort = "name"
      if params[:schedule_type]
        @regular_classes = RegularClass.order("name ASC").find_all_by_schedule_type_id(params[:schedule_type])
      else
        @regular_classes = RegularClass.order("name ASC").all
      end
    end


    @schedule_type = params[:schedule_type]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @regular_classes }
    end
  end

  # GET /regular_classes/1
  # GET /regular_classes/1.json
  def show
    @regular_class = RegularClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @regular_class }
    end
  end

  # GET /regular_classes/new
  # GET /regular_classes/new.json
  def new
    @regular_class = RegularClass.new

    teacher = []
    Teacher.all.each { |teach| teacher.push([teach.name, teach.id])}
    @teachers = teacher

    schedule_type = []
    ScheduleType.all.each { |sched| schedule_type.push([sched.name, sched.id])}
    @schedule_types = schedule_type

    @default_schedule_type = params[:schedule_type]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @regular_class }
    end
  end

  # GET /regular_classes/1/edit
  def edit
    teacher = []
    Teacher.all.each { |teach| teacher.push([teach.name, teach.id])}
    @teachers = teacher

    schedule_type = []
    ScheduleType.all.each { |sched| schedule_type.push([sched.name, sched.id])}
    @schedule_types = schedule_type

    @regular_class = RegularClass.find(params[:id])
  end

  # POST /regular_classes
  # POST /regular_classes.json
  def create
    @regular_class = RegularClass.new(params[:regular_class])

    respond_to do |format|
      if @regular_class.save
        format.html { redirect_to schedule_lessons_url(@regular_class), notice: 'Regular class was successfully created.' }
        format.json { render json: @regular_class, status: :created, location: @regular_class }
      else
        format.html { render action: "new" }
        format.json { render json: @regular_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /regular_classes/1
  # PUT /regular_classes/1.json
  def update
    @regular_class = RegularClass.find(params[:id])
    foo = params[:foo]

    respond_to do |format|
      if @regular_class.update_attributes(params[:regular_class])
        format.html { redirect_to @regular_class, notice: 'Regular class was successfully updated. ' + foo}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @regular_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /regular_classes/1/schedule_lessons
  def schedule_lessons
    @regular_class = RegularClass.find(params[:id])
    @schedule_type = @regular_class.schedule_type
    @holidays = []
    Holiday.where("schedule_type_id = ?", @schedule_type.id).pluck("Date(date)").each { |holiday| @holidays.push(holiday.to_s)}
    @lessons = []
    Lesson.where("regular_class_id = ?", params[:id]).pluck("Date(date)").each {|lesson| @lessons.push(lesson.to_s)}
  end

  # POST /regular_classes/1/create_lessons
  def create_lessons
    @regular_class = RegularClass.find(params[:id])
    dates = params[:dates]
    logger.info("Starting log...")
    Lesson.where("regular_class_id = ?", params[:id]).each do |l|
      logger.info("Destroying lesson for: " + l.date.to_s)
      l.destroy
    end

    lessons = 0
    if dates then 
      dates.each do |d|
        lesson = Lesson.new(:date => d, 
          :regular_class_id => params[:id], 
          :start_time => @regular_class.start_time, 
          :finish_time => @regular_class.finish_time, 
          :teaching_time => @regular_class.teaching_time, 
          :non_teaching_time => @regular_class.non_teaching_time, 
          :teacher_id => @regular_class.teacher_id, 
          :name => @regular_class.name,
          :status => Lesson::Status::OK)
        if lesson.save then 
          lessons = lessons + 1
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to regular_classes_url(:schedule_type => @regular_class.schedule_type_id), :flash => { :alert => "add_lessons", :class_name => @regular_class.name, :count => lessons.to_s }}
    end
  end

  # DELETE /regular_classes/1
  # DELETE /regular_classes/1.json
  def destroy
    @regular_class = RegularClass.find(params[:id])
    @regular_class.destroy

    respond_to do |format|
      format.html { redirect_to regular_classes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/regular_classes_helper.rb
module RegularClassesHelper
end

app/views/regular_classes/_form.html.haml
:javascript
  $(function(){
    $("#time_fields_container").find("select").change(function(){
      var start_min = (Number($("#regular_class_start_time_4i").val()) * 60) + Number($("#regular_class_start_time_5i").val());
      var finish_min = (Number($("#regular_class_finish_time_4i").val()) * 60) + Number($("#regular_class_finish_time_5i").val());
      var min = finish_min - start_min;
      if(min >= 0){
        $("#regular_class_teaching_time").val(min);
      }
    });

    var default_schedule_type = "#{@default_schedule_type}";
    if(default_schedule_type != ""){
      $("#regular_class_schedule_type_id").val(default_schedule_type);
    }
  });

= form_for(@regular_class, :html => {:class => "form-horizontal"}) do |f|
  - if @regular_class.errors.any?
    #error_explanation
      %h2
        = pluralize(@regular_class.errors.count, "error")
        prohibited this regular_class from being saved:
      %ul
        - @regular_class.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    %label.control-label Class Name
    .controls
      = f.text_field :name
  .control-group
    %label.control-label Schedule Type
    .controls
      = f.select :schedule_type_id, @schedule_types
  .control-group
    %label.control-label Day
    .controls
      = f.select :day, [["Free", -1], ["Monday", 1], ["Tuesday", 2], ["Wednesday", 3], ["Thursday", 4], ["Friday", 5], ["Saturday", 6], ["Sunday", 0]]
  #time_fields_container
    .control-group
      %label.control-label Start
      .controls
        = f.time_select :start_time, {:minute_step => 5}, {"class" => "input-mini"}
    .control-group
      %label.control-label Finish
      .controls
        = f.time_select :finish_time, {:minute_step => 5}, {"class" => "input-mini"}
  .control-group
    %label.control-label Teaching Time
    .controls
      .input-append
        = f.number_field :teaching_time, {"class" => "input-mini", "style" => "text-align: right;"}
        %span.add-on minutes
  .control-group
    %label.control-label Non-teaching Time
    .controls
      .input-append
        = f.number_field :non_teaching_time, {"class" => "input-mini", "style" => "text-align: right;"}
        %span.add-on minutes
  .control-group
    %label.control-label Textbook
    .controls
      = f.text_field :textbook
  .control-group
    %label.control-label Location
    .controls
      = f.text_field :location
  .control-group
    %label.control-label Teacher
    .controls
      = f.select :teacher_id, @teachers
  .control-group
    .controls
      .actions
        = f.submit "Create", :class => "btn btn-primary"

app/views/regular_classes/edit.html.haml
:javascript
  $(function(){

  });
%h1 Editing regular_class
= render 'form'
= link_to 'Show', @regular_class
|
\#{link_to 'Back', regular_classes_path}

app/views/regular_classes/index.html.haml
:javascript
  $(function(){
    //switch("#{@sort}"){
    //  case "na"
    //}
    $("#sort_#{@sort}").addClass("btn-info");
  });

- if flash[:alert]
  .alert.alert-success.alert-block.fade.in
    %button.close{:type => "button", :data => {:dismiss => "alert"}}
      &times;
    - case flash[:alert]
      - when "add_lessons"
        %h4 Regular Class Updated
        = 'A total of ' + flash[:count] + ' lessons have been scheduled for "' + flash[:class_name] + '"' 
      - when "delete"
        %h4 Schedule Type Deleted
%br/
- if @schedule_type
  = link_to new_regular_class_path(:schedule_type => @schedule_type), :class => "btn" do
    %i.icon-plus-sign
    New Regular Class
- else
  = link_to new_regular_class_path, :class => "btn" do
    %i.icon-plus-sign
    New Regular Class

%br/
%br/
%table.table.table-bordered.table-hover
  %tr
    %th 
      Name
      = link_to regular_classes_path(:schedule_type => @schedule_type, :sort => "name"), :class => "btn btn-mini", :id => "sort_name" do
        %i.icon-arrow-down
    %th Teacher
    %th{:colspan => "2"} 
      Day & Time
      = link_to regular_classes_path(:schedule_type => @schedule_type, :sort => "day"), :class => "btn btn-mini", :id => "sort_day" do
        %i.icon-arrow-down
    %th
  - @regular_classes.each do |regular_class|
    %tr.middle
      %td= regular_class.name
      %td= regular_class.teacher ? regular_class.teacher.name : "---"
      %td= %w{SUN MON TUE WED THU FRI SAT FREE}[regular_class.day]
      %td= regular_class.start_time.strftime("%H:%M") + " - " + regular_class.finish_time.strftime("%H:%M")
      %td
        .btn-toolbar
          .btn-group
            = link_to regular_class, :class => "btn btn-small" do
              %i.icon-search
              Show
            = link_to schedule_lessons_url(regular_class), :class => "btn btn-small" do
              %i.icon-plus
              Add Lessons
            = link_to edit_regular_class_path(regular_class), :class => "btn btn-small" do
              %i.icon-edit
              Edit
            = link_to regular_class, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small" do
              %i.icon-trash
              Delete

app/views/regular_classes/new.html.haml
:javascript
  $(function(){

  });
%h1 New Regular Class
= render 'form'
= link_to 'Back', regular_classes_path

app/views/regular_classes/schedule_lessons.html.haml
:javascript
  $(function(){

    $('form').submit(function(data){
      console.log($(this).serializeArray());
      return true;
    });

    console.log("schedule_type = #{@schedule_type}");
    console.log("schedule_type.id = #{@schedule_type.id}");
  });

  function addAllDays(){
    $("td.day").not('.otherMonth').not('.selected').each(function(){
      toggleDay($(this));
    });
  }

  function removeAllDays(){
    $("td.day.selected").not('.otherMonth').each(function(){
      toggleDay($(this));
    });
  }

  function toggleDay(cell){
    //console.log($(cell).html());
    var checked = $(cell).children(".day_checkbox").prop("checked");
    if(checked == true){
      $(cell).children(".day_checkbox").prop("checked", false);
      $(cell).removeClass("selected");
    }else if(checked == false){
      $(cell).children(".day_checkbox").prop("checked", true);
      $(cell).addClass("selected");
    }
  }

%h2= "Add / Remove Lessons - " + @regular_class.name
- if @schedule_type.name != "Custom" then
  %a.btn{:onclick => "addAllDays()"}
    %i.icon-plus-sign
    Add All Days
  %a.btn{:onclick => "removeAllDays()"}
    %i.icon-minus-sign
    Remove All Days
  %br
= form_for @regular_class, :url => create_lessons_regular_class_path, :method => 'post' do |f|
  - (0..11).each do |m|
    - d = @schedule_type.start_date >> m
    = calendar_for(d.year, d.month, :yield_surrounding_days => false, :current_month => "%Y-%m") do |day|                                                  |
        if @holidays.include?(day.to_s) or day.sunday? or ( day.wday != @regular_class.day and @regular_class.day != -1 ) then                             |
          [day.day.to_s,                                                                                                                                   |
          {:value => day.to_s, :style => "background-color: #666666; cursor: default;"}]                                                                   |
        elsif @lessons.include?(day.to_s) then                                                                                                             |
          ["<input class='day_checkbox' type='checkbox' name='dates[]' value='" + day.to_s + "' style='display: none;' checked='checked'>" + day.day.to_s, |
          {:value => day.to_s, :onclick => "toggleDay(this)", :class => "selected"}]                                                                       |
        else                                                                                                                                               |
          ["<input class='day_checkbox' type='checkbox' name='dates[]' value='" + day.to_s + "' style='display: none;'>" + day.day.to_s,                   |
          {:value => day.to_s, :onclick => "toggleDay(this)"}]                                                                                             |
        end                                                                                                                                                |
      end                                                                                                                                                  |
  %br
    = link_to "Back", regular_classes_path(:schedule_type => @regular_class.schedule_type), :class => "btn"
    %a.btn.btn-primary{:onclick => "$('form.edit_regular_class').submit()"}
      Add / Remove Classes

app/views/regular_classes/show.html.haml
:javascript
  $(function(){

  });
%p#notice= notice
%p
  %b Length:
  = @regular_class.length
%p
  %b Start time:
  = @regular_class.start_time
%p
  %b Finish time:
  = @regular_class.finish_time
%p
  %b Textbook:
  = @regular_class.textbook
%p
  %b Name:
  = @regular_class.name
%p
  %b Location:
  = @regular_class.location
%p
  %b Day:
  = @regular_class.day
= link_to 'Edit', edit_regular_class_path(@regular_class)
|
\#{link_to 'Back', regular_classes_path}