config/routes.rb
Scheduler::Application.routes.draw do
  get "confirm/ok"
  get "confirm/staff_ok"

  get "confirm/ng"

  resources :notifications

  devise_for :users

  get "monthly_report/report"

  get "weekly_schedule/weekly"

  root :to => 'home#index'

  match 'lessons/add' => 'lessons#add', :as => :add_lesson

  resources :holidays
  resources :schedule_types
  resources :lessons
  resources :users
  resources :teachers do
    post 'set_availability', :on => :member
  end
  resources :regular_classes do
    post 'create_lessons', :on => :member
  end

  match 'schedule_types/:id/set_holidays' => 'schedule_types#set_holidays', :as => :set_holidays
  match 'lessons/:id/cancel' => 'lessons#cancel', :as => :cancel_lesson
  match 'lessons/:id/sub' => 'lessons#sub', :as => :sub_lesson
  match 'teachers/:id/send_test_mail' => 'teachers#send_test_mail', :as => :send_test_mail
  match 'teachers/:id/send_weekly_schedule_mail' => 'teachers#send_weekly_schedule_mail', :as => :send_weekly_schedule_mail
  match 'teachers/:id/availability' => 'teachers#availability', :as => :availability
  match 'regular_classes/:id/schedule_lessons' => 'regular_classes#schedule_lessons', :as => :schedule_lessons
  match ':date' => 'home#index', :as => :dailyschedule
  match 'weekly/:id' => 'weekly_schedule#weekly', :as => :weekly
  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  attr_accessible :name, :id, :email, :message_preference
  
  has_many :regular_classes
  has_many :lessons, :through => :regular_classes
  has_many :off_times

  def lessons_on(date)
    Lesson.where("date = ? AND teacher_id = ?", date, id)
  end

  def off_times_on(date)
    OffTime.where("day = ? AND teacher_id = ?", date.cwday, id)
  end

  def schedule_csv(options = {})
    year_lessons = Lesson.where("teacher_id = ?", id).order("date ASC").order("start_time ASC");
    CSV.generate(options) do |csv|
      csv << ["Subject", "Start Date", "Start Time", "End Date", "End Time"]
      year_lessons.each do |l|
        csv << [l.name, l.date, l.start_time.strftime('%H:%M'), l.date, l.finish_time.strftime('%H:%M')]
      end
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!
  require 'base64'
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.order("name ASC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
      format.csv { send_data @teacher.schedule_csv, :filename => (@teacher.name + " Schedule.csv")}
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  # GET /teachers/1/send_test_mail
  def send_test_mail
    @teacher = Teacher.find(params[:id])

    status = 0
    if ScheduleMailer.test_notice(@teacher).deliver
      status = 1
    end

    respond_to do |format|
      format.json { render json: {"status" => status} }
    end
  end

  # POST /teachers/1/send_weekly_schedule_mail
  def send_weekly_schedule_mail
    @teacher = Teacher.find(params[:id])
    @img_url = params[:img_url]
    image = Base64.decode64(@img_url)
    File.open("#{Rails.root}/test.png", 'wb') do|f|
      f.write(image)
    end
    status = 0
    if ScheduleMailer.test_notice(@teacher).deliver
      status = 1
    end

    respond_to do |format|
      format.json { render json: {"status" => status} }
    end
  end

  # GET /teachers/1/availability
  def availability
    @teacher = Teacher.find(params[:id])
    @off_times = OffTime.order("day ASC").order("start_time ASC").find_all_by_teacher_id(params[:id])
  end

  # POST /teachers/1/set_availability
  def set_availability
    @teacher = Teacher.find(params[:id])

    start_times = params[:start_times]
    finish_times = params[:finish_times]
    days = params[:days]

    OffTime.where("teacher_id = ?", params[:id]).each do |o|
      puts "Deleting off time: " + o.start_time.to_s + " - " + o.finish_time.to_s
      o.destroy
    end
    start_times.zip(finish_times, days).each do |sf|
      start_time = sf[0].split(":")
      finish_time = sf[1].split(":")
      off_time = OffTime.new(:start_time => Time.utc(2000, 1, 1, start_time[0], start_time[1], 0), :finish_time => Time.utc(2000, 1, 1, finish_time[0], finish_time[1], 0), :day => sf[2], :teacher_id => params[:id])
      puts "Saving time off for " + sf[0] + " - " + sf[1] + " (day " + sf[2] + ")"
      if off_time.save
        puts "Saved"
      end
    end
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.haml
= form_for(@teacher) do |f|
  - if @teacher.errors.any?
    #error_explanation
      %h2
        = pluralize(@teacher.errors.count, "error")
        prohibited this teacher from being saved:
      %ul
        - @teacher.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :message_preference
    %br/
    = f.select :message_preference, [["No automatic e-mails", 0], ["Notify only before days with urgent classes", 1], ["Notify before any day with classes", 2]]  
  .actions
    = f.submit

app/views/teachers/availability.html.haml
:javascript
  $(function(){

  });

  function addOffTimeRow(){
    var day_of_week = $("#day_of_week").val(),
      start_hours = $("#start_time_hours").val(),
      start_minutes = $("#start_time_minutes").val(),
      finish_hours = $("#finish_time_hours").val(),
      finish_minutes = $("#finish_time_minutes").val()
    ;
    //alert("From " + start_hours + ":" + start_minutes + " to " + finish_hours + ":" + finish_minutes);

    var new_row = $(".new_off_time_row").clone().removeClass("new_off_time_row");
    $(new_row).children(".time_text").html(start_hours + ":" + start_minutes + " ~ " + finish_hours + ":" + finish_minutes)
    $(new_row).children(".day_of_week").val(day_of_week);
    $(new_row).children(".start_time").val(start_hours + ":" + start_minutes);
    $(new_row).children(".finish_time").val(finish_hours + ":" + finish_minutes);
    $("#day_of_week_" + day_of_week).append(new_row);
  }

  function deleteRow(link_element){
    $(link_element).parent().remove();
  }

%h2 Unavailable Time for #{@teacher.name}
%form
  %table
    %tr
      %td Day
      %td From
      %td Until
      %td
    %tr
      %td{:style => "padding-right: 20px;"}
        %select#day_of_week
          %option{:value => "1"} Monday
          %option{:value => "2"} Tuesday
          %option{:value => "3"} Wednesday
          %option{:value => "4"} Thursday
          %option{:value => "5"} Friday
          %option{:value => "6"} Saturday
      %td{:style => "padding-right: 20px;"}
        = select_tag(:start_time_hours, options_for_select(9..21), {:class => "input-mini"})
        = ":"
        = select_tag(:start_time_minutes, options_for_select(["00", "05", 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]), {:class => "input-mini"})
      %td{:style => "padding-right: 20px;"}
        = select_tag(:finish_time_hours, options_for_select(9..21), {:class => "input-mini"})
        = ":"
        = select_tag(:finish_time_minutes, options_for_select(["00", "05", 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]), {:class => "input-mini"})
      %td
        %input.btn{:type => "button", :value => "Add", :style => "line-height: 30px; margin-bottom: 10px;", :onclick => "addOffTimeRow()"}
%ul{:style => "display: none;"}
  %li.new_off_time_row
    %span.time_text Hi!
    %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
    %input.day_of_week{:name => "days[]", :type => "hidden"}
    %input.start_time{:name => "start_times[]", :type => "hidden"}
    %input.finish_time{:name => "finish_times[]", :type => "hidden"}
= form_tag(:controller => "teachers", :action => "set_availability", :id => "#{@teacher.id}") do
  %h4 Monday
  %ul#day_of_week_1
    - @off_times.each do |o|
      - if o.day == 1
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %h4 Tuesday
  %ul#day_of_week_2
    - @off_times.each do |o|
      - if o.day == 2
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %h4 Wednesday
  %ul#day_of_week_3
    - @off_times.each do |o|
      - if o.day == 3
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %h4 Thursday
  %ul#day_of_week_4
    - @off_times.each do |o|
      - if o.day == 4
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %h4 Friday
  %ul#day_of_week_5
    - @off_times.each do |o|
      - if o.day == 5
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %h4 Saturday
  %ul#day_of_week_6
    - @off_times.each do |o|
      - if o.day == 6
        %li
          %span.time_text= o.start_time.strftime("%H:%M") + " ~ " + o.finish_time.strftime("%H:%M")
          %a{:onclick => "deleteRow(this)", :style => "cursor: pointer;"} X
          %input.day_of_week{:name => "days[]", :type => "hidden", :value => "#{o.day}"}
          %input.start_time{:name => "start_times[]", :type => "hidden", :value => "#{o.start_time.strftime('%H:%M')}"}
          %input.finish_time{:name => "finish_times[]", :type => "hidden", :value => "#{o.finish_time.strftime('%H:%M')}"}
  %input.btn.btn-primary{:type => "submit", :value => "Save"}

app/views/teachers/edit.html.haml
:javascript
  $(function(){

  });
%h1 Editing teacher
= render 'form'
= link_to 'Show', @teacher
|
\#{link_to 'Back', teachers_path}

app/views/teachers/index.html.haml
:javascript
  $(function(){

  });

  function sendTestMail(teacher_id, link){
    $.ajax({
      url: "teachers/" + teacher_id + "/send_test_mail.json?id=" + teacher_id,
    }).done(function(response){
      if(response.status == "1"){
        alert("Mail Sent");
      }else{
        alert("Could not send mail.");
      }
    });
  }

%table.table.table-striped
  %tr
    %th Name
    %th
    %th
    %th
    %th
    %th
  - @teachers.each do |teacher|
    %tr
      %td= teacher.name
      %td= link_to 'Show', teacher
      %td= link_to 'CSV', "teachers/" + teacher.id.to_s + ".csv"
      %td= link_to 'Edit', edit_teacher_path(teacher)
      %td= link_to 'Availability', availability_url(teacher)
      %td= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Teacher', new_teacher_path

app/views/teachers/new.html.haml
:javascript
  $(function(){

  });
%h1 New teacher
= render 'form'
= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
:javascript
  $(function(){

  });
%p#notice= notice
%table.table
  %tr
    %td Name
    %td= @teacher.name
%p Regular Classes
%table.table
  - @teacher.regular_classes.all.each do |regular_class|
    %tr
      %td= regular_class.name
= link_to 'Edit', edit_teacher_path(@teacher)
|
\#{link_to 'Back', teachers_path}